### ISSUE TITLE
NPE on scala 2.10 for version 0.8

### ISSUE THREAD

**Issue by lawrencefinn** [lightbend/genjavadoc#46]
uncaught exception during compilation: java.lang.NullPointerException

```
java.lang.NullPointerException
    at com.typesafe.genjavadoc.GenJavaDocPlugin.outputBase$lzycompute(Plugin.scala:47)
    at com.typesafe.genjavadoc.GenJavaDocPlugin.outputBase(Plugin.scala:47)
    at com.typesafe.genjavadoc.GenJavaDocPlugin$MyComponent$GenJavaDocTransformer.<init>(Plugin.scala:68)
    at com.typesafe.genjavadoc.GenJavaDocPlugin$MyComponent$.newTransformer(Plugin.scala:63)
    at com.typesafe.genjavadoc.GenJavaDocPlugin$MyComponent$.newTransformer(Plugin.scala:51)
    at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
    at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:464)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:431)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:431)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
    at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:431)
    at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1583)
    at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1557)
    at scala.tools.nsc.Global$Run.compileSources(Global.scala:1553)
    at scala.tools.nsc.Global$Run.compile(Global.scala:1662)
    at xsbt.CachedCompiler0.run(CompilerInterface.scala:123)
    at xsbt.CachedCompiler0.run(CompilerInterface.scala:99)
```

Works fine on 2.11

**Comment by rkuhn** [comment]
Which Scala version fails exactly? Does this still happened with 0.9? It seems that `processOptions` was not called by the compiler before starting the compilation run.

**Comment by SethTisue** [comment]
closing for staleness
